### ISSUE TITLE
laravel6.0

### ISSUE THREAD

**Issue by wl496928838** [laravel-admin-extensions/reporter#12]
Dependency resolution completed in 0.052 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/framework (locked at v6.4.0, required as ^6.0) -> satisfiable by laravel/framework[v6.4.0].
    - Conclusion: don't install laravel-admin-ext/reporter v1.0.1
    - Can only install one of: encore/laravel-admin[1.5.x-dev, v1.7.7].
    - Can only install one of: encore/laravel-admin[v1.7.7, 1.5.x-dev].
    - Can only install one of: encore/laravel-admin[1.5.x-dev, v1.7.7].
    - laravel-admin-ext/reporter v1.0.0 requires encore/laravel-admin 1.5.* -> satisfiable by encore/laravel-admin[1.5.x-dev].
    - Installation request for laravel-admin-ext/reporter ^1.0 -> satisfiable by laravel-admin-ext/reporter[v1.0.0, v1.0.1].
    - Installation request for encore/laravel-admin (locked at v1.7.7, required as ^1.7) -> satisfiable by encore/laravel-admin[v1.7.7].

Installation failed, reverting ./composer.json to its original content.

**Comment by schel4ok** [comment]
upgrade is planned?

**Comment by z-song** [comment]
New version released

**Comment by schel4ok** [comment]
still cannot install
encore/laravel-admin | ^1.7
laravel/framework | ^6.2

```
Dependency resolution completed in 0.199 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/framework (locked at v6.6.2, required as ^6.2) -> satisfiable by laravel/framework[v6.6.2].
    - Conclusion: don't install laravel-admin-ext/reporter v1.0.1
    - Can only install one of: encore/laravel-admin[1.5.x-dev, v1.7.8].
    - Can only install one of: encore/laravel-admin[v1.7.8, 1.5.x-dev].
    - Can only install one of: encore/laravel-admin[1.5.x-dev, v1.7.8].
    - laravel-admin-ext/reporter v1.0.0 requires encore/laravel-admin 1.5.* -> satisfiable by encore/laravel-admin[1.5.x-dev].
    - Installation request for laravel-admin-ext/reporter ^1.0 -> satisfiable by laravel-admin-ext/reporter[v1.0.0, v1.0.1].
    - Installation request for encore/laravel-admin (locked at v1.7.8, required as ^1.7) -> satisfiable by encore/laravel-admin[v1.7.8].


Installation failed, reverting ./composer.json to its original content.
```
